/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandStrategyRouteImport } from './routes/brand-strategy'
import { Route as BusinessStrategyRouteImport } from './routes/business-strategy'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ConnectWithUsRouteImport } from './routes/connect-with-us'
import { Route as MarketResearchRouteImport } from './routes/market-research'
import { Route as QualitativeResearchRouteImport } from './routes/qualitative-research'
import { Route as QuantitativeResearchRouteImport } from './routes/quantitative-research'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StrategyExecutionRouteImport } from './routes/strategy-execution'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandStrategyRoute = BrandStrategyRouteImport.update({
  id: '/brand-strategy',
  path: '/brand-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessStrategyRoute = BusinessStrategyRouteImport.update({
  id: '/business-strategy',
  path: '/business-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectWithUsRoute = ConnectWithUsRouteImport.update({
  id: '/connect-with-us',
  path: '/connect-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketResearchRoute = MarketResearchRouteImport.update({
  id: '/market-research',
  path: '/market-research',
  getParentRoute: () => rootRouteImport,
} as any)
const QualitativeResearchRoute = QualitativeResearchRouteImport.update({
  id: '/qualitative-research',
  path: '/qualitative-research',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantitativeResearchRoute = QuantitativeResearchRouteImport.update({
  id: '/quantitative-research',
  path: '/quantitative-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyExecutionRoute = StrategyExecutionRouteImport.update({
  id: '/strategy-execution',
  path: '/strategy-execution',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/business-strategy': typeof BusinessStrategyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/connect-with-us': typeof ConnectWithUsRoute
  '/market-research': typeof MarketResearchRoute
  '/qualitative-research': typeof QualitativeResearchRoute
  '/quantitative-research': typeof QuantitativeResearchRoute
  '/services': typeof ServicesRoute
  '/strategy-execution': typeof StrategyExecutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/business-strategy': typeof BusinessStrategyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/connect-with-us': typeof ConnectWithUsRoute
  '/market-research': typeof MarketResearchRoute
  '/qualitative-research': typeof QualitativeResearchRoute
  '/quantitative-research': typeof QuantitativeResearchRoute
  '/services': typeof ServicesRoute
  '/strategy-execution': typeof StrategyExecutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/business-strategy': typeof BusinessStrategyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/connect-with-us': typeof ConnectWithUsRoute
  '/market-research': typeof MarketResearchRoute
  '/qualitative-research': typeof QualitativeResearchRoute
  '/quantitative-research': typeof QuantitativeResearchRoute
  '/services': typeof ServicesRoute
  '/strategy-execution': typeof StrategyExecutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand-strategy'
    | '/business-strategy'
    | '/case-studies'
    | '/connect-with-us'
    | '/market-research'
    | '/qualitative-research'
    | '/quantitative-research'
    | '/services'
    | '/strategy-execution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand-strategy'
    | '/business-strategy'
    | '/case-studies'
    | '/connect-with-us'
    | '/market-research'
    | '/qualitative-research'
    | '/quantitative-research'
    | '/services'
    | '/strategy-execution'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brand-strategy'
    | '/business-strategy'
    | '/case-studies'
    | '/connect-with-us'
    | '/market-research'
    | '/qualitative-research'
    | '/quantitative-research'
    | '/services'
    | '/strategy-execution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandStrategyRoute: typeof BrandStrategyRoute
  BusinessStrategyRoute: typeof BusinessStrategyRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ConnectWithUsRoute: typeof ConnectWithUsRoute
  MarketResearchRoute: typeof MarketResearchRoute
  QualitativeResearchRoute: typeof QualitativeResearchRoute
  QuantitativeResearchRoute: typeof QuantitativeResearchRoute
  ServicesRoute: typeof ServicesRoute
  StrategyExecutionRoute: typeof StrategyExecutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-strategy': {
      id: '/brand-strategy'
      path: '/brand-strategy'
      fullPath: '/brand-strategy'
      preLoaderRoute: typeof BrandStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-strategy': {
      id: '/business-strategy'
      path: '/business-strategy'
      fullPath: '/business-strategy'
      preLoaderRoute: typeof BusinessStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-with-us': {
      id: '/connect-with-us'
      path: '/connect-with-us'
      fullPath: '/connect-with-us'
      preLoaderRoute: typeof ConnectWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-research': {
      id: '/market-research'
      path: '/market-research'
      fullPath: '/market-research'
      preLoaderRoute: typeof MarketResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualitative-research': {
      id: '/qualitative-research'
      path: '/qualitative-research'
      fullPath: '/qualitative-research'
      preLoaderRoute: typeof QualitativeResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantitative-research': {
      id: '/quantitative-research'
      path: '/quantitative-research'
      fullPath: '/quantitative-research'
      preLoaderRoute: typeof QuantitativeResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-execution': {
      id: '/strategy-execution'
      path: '/strategy-execution'
      fullPath: '/strategy-execution'
      preLoaderRoute: typeof StrategyExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandStrategyRoute: BrandStrategyRoute,
  BusinessStrategyRoute: BusinessStrategyRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ConnectWithUsRoute: ConnectWithUsRoute,
  MarketResearchRoute: MarketResearchRoute,
  QualitativeResearchRoute: QualitativeResearchRoute,
  QuantitativeResearchRoute: QuantitativeResearchRoute,
  ServicesRoute: ServicesRoute,
  StrategyExecutionRoute: StrategyExecutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
